Rename Variable to BallSize
pret/pokepinball pull request #49
Opened 2023-12-11 23:44 UTC by NicoleFaye

Identified Var as ball size.

2023-12-12 01:00 UTC, huderlem requested changes
The name `wBallSize` seems good to me.  However, you'll have to revert/fix the changes to `wd4c7`, since that results in an incorrect ROM.

2023-12-12 01:00 UTC, huderlem commented on engine/pinball_game/draw_sprites/draw_pinball.asm
> -	ld a, [wd4c7]
In a couple places, `wd4c7` was mistakenly replaced with `wBallSize`.

2023-12-12 01:23 UTC, NicoleFaye commented
my bad, I thought I undid that mistake, it should be fixed now.

2023-12-13 19:31 UTC, NicoleFaye commented on engine/pinball_game/draw_sprites/draw_pinball.asm
> -	ld a, [wd4c7]
Adjusted

2023-12-13 23:48 UTC, merged